#!/bin/sh

# Copyright (C) 2009 OpenWrt.org

# echo ACTION=$ACTION, DEVPATH=$DEVPATH, SUBSYSTEM=$SUBSYSTEM, BUSNUM=$BUSNUM >/dev/console

# echo "--------------" >>/dev/console
#echo "busnum=$BUSNUM" >> /dev/console
#echo "action=$ACTION" >> /dev/console
#echo "intf=$INTERFACE" >> /dev/console
#echo "devnum=$DEVNUM" >> /dev/console
#echo "dev=$DEVICE" >> /dev/console
#echo "pdt=$PRODUCT" >> /dev/console
#echo "type=$TYPE" >> /dev/console
#echo "--------------" >>/dev/console

PORTNUM=`echo $DEVPATH | cut -d "-" -f 3 | cut -d "/" -f 1`

echo "USB port event happened -- port=$PORTNUM" >> /dev/console
case "$PORTNUM" in
    1)
        USB="USB1"
        ;;
    2)
        USB="USB1"
        ;;
    *)
        exit 0
        ;;
esac

case "$ACTION" in
	add)
		# update LEDs
		if [ -f /tmp/modem/modem_handling ] || [ -f /tmp/modem/modem_handled ]; then
			echo "[hotplug]10-usb don't twinkle LED when modem is on." >/dev/console
		else
			echo "[hotplug]10-usb trigger USB1 twinkle----" >/dev/console
			ledcli ${USB}_twinkle
		fi

		;;
	remove)
		# update LEDs
		if [ -f /tmp/modem/modem_handling ]; then
			echo "[hotplug]10-usb don't turn off LED when modem is on." >/dev/console
		else
			echo "[hotplug]10-usb turn off LED----" >/dev/console
			uci set ledctrl.$USB.ledon='0'
			ledcli $USB
		fi
		;;
esac	
		
