#!/bin/sh

# echo ACTION=$ACTION, DEVPATH=$DEVPATH, SUBSYSTEM=$SUBSYSTEM, BUSNUM=$BUSNUM >/dev/console

case "$ACTION" in
        add)
            ps |grep "sh /lib/time_machine/tm_usb_add.sh" |grep -v grep |awk '{print $1}' |xargs kill -9
            sh /lib/time_machine/tm_usb_add.sh &
            ;;
        remove)
            sh /lib/time_machine/tm_usb_remove.sh
            ;;
esac
