#!/bin/sh

WIRELESS_SCHEDULE_LIBDIR=/lib/wifi
. ${WIRELESS_SCHEDULE_LIBDIR}/wireless_schedule_func.sh

. /lib/functions.sh

cmd=$1
shift

SYS_SET_TIME=$(uci_get_state systime core sync)

case $cmd in
    *ACTIVE)
		if [ $SYS_SET_TIME -eq 1 ]; then
			config_load wireless_schedule
			config_get enable "$1" enable
			if [ "$enable" = "off" ]; then
				/etc/init.d/wireless_schedule restart
			else
				wireless_schedule_handle_active "$1"
			fi
		fi
        ;;

    *DORM)
		if [ $SYS_SET_TIME -eq 1 ]; then
				wireless_schedule_handle_dorm "$1"
		fi
        ;;
esac

