#!/bin/sh
# Copyright(c) 2011-2014 Shenzhen TP-LINK Technologies Co.Ltd.
# file     ftpex
# brief    
# author   Zhu Xianfeng<zhuxianfeng@tp-link.net>
# version  1.0.0
# date     25Jun14
# history  arg 1.0.0, 25Jun14, Zhu Xianfeng, Create the file. 

. /lib/switch/core_phy.sh

if [ $# -eq 1 ] && [ "$1" = "init" ] ; then
    local port=$(uci get portspeed.wan.port)
    local speed=$(uci get portspeed.wan.current)
    case $speed in
        auto)
            ;;
        1000F)
            speed=1000MFD
            ;;
        1000H)
            speed=1000MHD
            ;;
        100F)
            speed=100MFD
            ;;
        100H)
            speed=100MHD
            ;;
        10F)
            speed=10MFD
            ;;
        10H)
            speed=10MHD
            ;;
        *)
            exit 1
        ;;
    esac
    set_port_duplex $port $speed
else
    if [ $# -ne 4 ]; then
        exit 1
    fi
    local port=$1
    local speed=$2
    local duplex=$3
    local autoneg=$4

    case $speed in
        1000)
            ;;
        100)
            ;;
        10)
            ;;
        *)
            exit 1
            ;;
    esac

    if [ "$duplex" != "full" -a "$duplex" != "half" ]; then
        exit 1
    fi
    if [ "$autoneg" != "on" -a "$autoneg" != "off" ]; then
        exit 1
    fi

    if [ "$speed" = "1000" -o "$autoneg" = "on"  ] ; then
        set_port_duplex $port "auto"
    else
        local duplexTmp="HD"
        [ "$duplex" == "full" ] && duplexTmp="FD"
        local media_type="${speed}M${duplexTmp}"
        set_port_duplex $port $media_type
    fi
fi
