#!/bin/sh

local model=`getfirm MODEL`

if [ "$model" = "Archer A6" ] ; then
	uci set locale.sysinfo.model="A6 MU-MIMO Wi-Fi Router"
	echo locale.sysinfo.model="A6 MU-MIMO Wi-Fi Router" > /dev/console
elif [ "$model" = "Archer C6" ] ; then
	uci set locale.sysinfo.model="C6 MU-MIMO Wi-Fi Router"
	echo locale.sysinfo.model="C6 MU-MIMO Wi-Fi Router" > /dev/console
fi

uci commit
