#!/bin/sh

favicon_partition="favicon"
logo_partiton="logo"

nvrammanager -e -p ag-config
nvrammanager -e -p  $favicon_partition
nvrammanager -e -p  $logo_partiton
lua -e 'require("luci.controller.admin.firmware").config_factory()'
sleep 3
reboot -f 
