#!/bin/sh

switch_mode_lock() {
	echo " =========================== SWITCH MODE LOCK =========================="  >/dev/console
	touch /var/run/switch_mode.lock
}

switch_mode_unlock() {
	rm /var/run/switch_mode.lock
	echo " ========================== SWITCH MODE UNLOCK =========================" >/dev/console
}

rtoa() {
	local section_line

	# lock to disable saveconfig otherwhere
	switch_mode_lock
	
	nvrammanager -r /tmp/user-config -p user-config
	nvrammanager -w /tmp/user-config -p router-config
	nvrammanager -r /tmp/ap-config -p ap-config
	if [ -s "/tmp/ap-config" ];then
		nvrammanager -w /tmp/ap-config -p user-config
		echo "-----------------ap-config is not null--------------" >/dev/console
	else
		section_line=$(uci show|grep 'sysmode.ap'|wc -l)
		if [ $section_line -gt 1 ];then
			echo "-----------------section line gt 1--------------" >/dev/console
			switch_mode_oldway
			nvrammanager -r /tmp/ap-config -p user-config
			nvrammanager -w /tmp/ap-config -p ap-config
		else
			echo "-----------------section line lt 1--------------" >/dev/console
			nvrammanager -r /tmp/ap-def-config -p ap-def-config
			nvrammanager -w /tmp/ap-def-config -p ap-config
			nvrammanager -w /tmp/ap-def-config -p user-config
			remodel_ap_merge
		fi
		echo "-----------------ap-config is null--------------" >/dev/console
	fi
	echo "-------------sync start----------" >/dev/console
	sync_mode_file
	echo "-------------sync end----------" >/dev/console
	rm -f /tmp/user-config /tmp/ap-config /tmp/ap-def-config 
	reboot
}

ator() {
	# lock to disable saveconfig otherwhere
	switch_mode_lock
	
	nvrammanager -r /tmp/user-config -p user-config
	nvrammanager -w /tmp/user-config -p ap-config
	nvrammanager -r /tmp/router-config -p router-config
	if [ -s "/tmp/router-config" ]; then
		nvrammanager -w /tmp/router-config -p user-config
	else
		echo "-----------------router-config is null--------------" >/dev/console
		switch_mode_oldway
		nvrammanager -r /tmp/router-config -p user-config
		nvrammanager -w /tmp/router-config -p router-config
	fi
	sync_mode_file
	rm -f /tmp/user-config /tmp/router-config
	reboot
}

act=$1
case "$act" in
	rtoa)	    rtoa ;;
	ator)	    ator ;;
	*)	    ;;
esac
