#!/bin/sh

#insert usbhost & scsi modules
 
insmod_usbhost_scsi() {
	insmod /lib/modules/*/kernel/drivers/usb/host/ehci-hcd.ko  
	insmod /lib/modules/*/kernel/drivers/usb/host/ehci-platform.ko  
	insmod /lib/modules/*/kernel/drivers/usb/host/ohci-hcd.ko  
	insmod /lib/modules/*/kernel/drivers/usb/host/xhci-hcd.ko  

	insmod /lib/modules/*/kernel/drivers/usb/storage/usb-storage.ko
	insmod hfs
	insmod hfsplus


}

boot_hook_add preinit_main insmod_usbhost_scsi 

