#!/bin/sh

#add directories here

RAMFS_DIRS="/etc/ /lib/wifi/ /usr/lib/lua /www/webpages/logo /www/webpages/themes/green/img /www/webpages/module /www/webpages/pages/frame"
 
rootfs_init_etc_ramfs() {
    for dir in $RAMFS_DIRS;
    do
        tmp_dir=/tmp/`basename ${dir}`_tmp
        cp -a ${dir} ${tmp_dir}
        mount -t ramfs -n none ${dir}
        cp -a ${tmp_dir}/* ${dir}
        rm -rf ${tmp_dir} 
    done
}

boot_hook_add preinit_mount_root rootfs_init_etc_ramfs
