#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=47

AC_LIBDIR=/lib/access_control

ac() {
	. $AC_LIBDIR/core.sh
	fw_$1
}

start() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
	ac start
	fi
}

stop() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
	ac stop
	fi
}

restart() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
	ac restart
	fi
}

reload() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
	ac reload
	fi
}
