#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org
. /lib/functions.sh

START=50
SERVICE_DAEMONIZE=1

start() {
	config_load /etc/config/factory

	# as mergeconfig will automatically add config,this part is basically not useful.Keep it for mergeconfig fail case.
	if [ -z "$(config_get agileconfig enable)" ]; then
		echo "[agileconfig] no agile config flag, create!" > /dev/console
		uci set factory.agileconfig='global'
		uci set factory.agileconfig.enable="no"
		uci commit
	fi

	#for old FW(don't support agile) upgrade to new FW,turn agile config flag off.
	if [ -z "$(config_get factorymode agileOldToNew)" ]; then
		uci set factory.agileconfig.enable="no"
		uci commit
	fi

	config_load /etc/config/ledctrl
	if [ -z "$(config_get ALL_LED_ON ledname)" -o -z "$(config_get ALL_LED_ON ledname)" ]; then
		echo "[agileconfig] no ALL_LED config, create!" > /dev/console
		uci set ledctrl.ALL_LED_ON='rule'
		uci set ledctrl.ALL_LED_ON.style="default"
		uci set ledctrl.ALL_LED_ON.ledon="1"
		uci set ledctrl.ALL_LED_ON.ledname="ALL_LED"
		uci set ledctrl.ALL_LED_OFF='rule'
		uci set ledctrl.ALL_LED_OFF.style="default"
		uci set ledctrl.ALL_LED_OFF.ledon="0"
		uci set ledctrl.ALL_LED_OFF.ledname="ALL_LED"
		uci commit
	fi

	config_load /etc/config/sysmode
	if [ "$(config_get sysmode mode)" = "ap" ]; then
		echo "[agileconfig] the sysmode is ap, the agile config won't used!" > /dev/console
		uci set factory.agileconfig.enable="no"
		uci commit
	fi

	config_load /etc/config/factory
	if [ "$(config_get agileconfig enable)" = "no" ]; then
		if [ -f /tmp/agileconfig_1h_counts ];then
			rm /tmp/agileconfig_1h_counts
		fi
	fi	
	return 0
}

