#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=15

guest_access_func() {
	local guest_ifname_2g=$(uci get profile.@wireless[0].wireless_guest_ifname_2g -c "/etc/profile.d" -q)
	local cfg="$1"
	local local_access_enable=

	[ "$guest_ifname_2g" = "" ] && guest_ifname_2g="wl0.1"
	
	config_get enable "$cfg" enable
    [ "$enable" = "on" ] || return 0 
	
	config_get guest "$cfg" guest
    [ "$guest" = "on" ] || return 0

	config_get ifname "$cfg" ifname
    [ "$ifname" = "$guest_ifname_2g" ] || return 0

	config_get_bool local_access_enable "$cfg" access 0
	echo "$local_access_enable" > /proc/bridge_filter/local_access_flag	
}

start() {
	local device_list=
	local guest_ifname_2g=$(uci get profile.@wireless[0].wireless_guest_ifname_2g -c "/etc/profile.d" -q)
	local guest_ifname_5g=$(uci get profile.@wireless[0].wireless_guest_ifname_5g -c "/etc/profile.d" -q)
	local guest_ifname_5g_2=$(uci get profile.@wireless[0].wireless_guest_ifname_5g_2 -c "/etc/profile.d" -q)
	local support_triband=$(uci get profile.@wireless[0].support_triband -c "/etc/profile.d" -q)			

	if [ "$guest_ifname_2g" = "" ];then
		device_list="$device_list wl0.1"
	else
		device_list="$device_list $guest_ifname_2g"
	fi
	if [ "$guest_ifname_5g" = "" ];then
		device_list="$device_list wl1.1"
	else
		device_list="$device_list $guest_ifname_5g"
	fi

	[ "$support_triband" = "yes" ] && {
		if [ "$guest_ifname_5g_2" = "" ];then
			device_list="$device_list wl2.1"
		else
			device_list="$device_list $guest_ifname_5g_2"
		fi
	}

	config_load wireless
	config_foreach guest_access_func wifi-iface

	echo "$device_list" > /proc/bridge_filter/device_list
}

