#!/bin/sh /etc/rc.common

START=99
SERVICE_DAEMONIZE=1

boot()
{
	start

	#check upgrade
	[ -f /usr/sbin/cloud_https_bootreq ] && {
		ps -w |grep -v grep |grep "/usr/sbin/cloud_https_bootreq" > /dev/null 2>&1
		[ $? -eq 0 ] || /usr/sbin/cloud_https_bootreq &
	}
}

start()
{
	service_start /usr/bin/cloud-https -c /etc/cloud_https.cfg
}

stop()
{
	service_stop /usr/bin/cloud-https -c /etc/cloud_https.cfg
}

restart()
{
	stop
	start
}
