#!/bin/sh /etc/rc.common

START=99
boot()
{
	start
}


start()
{
	local nat_enable=$(uci get nat.@nat_global[0].enable)
	local hw_enable=$(uci get nat.@nat_global[0].hw_enable)
	[ "$hw_enable" == "off" ] && {
		stop
		return
	}
	[ ! -f /lib/modules/*/kernel/net/nat/hw_nat/hw_nat.ko ] && return
	lsmod |grep -q "hw_nat" || {
		insmod /lib/modules/*/kernel/net/nat/hw_nat/hw_nat.ko
		. /lib/network/network_arch.sh
		config_load network
		local proto l3_device wanv6_vid
		config_get proto wan proto "dslite"
		config_get l3_device wan ifname "eth1.1"
		if [ "$proto" == "v6plus" ];then
			wanv6_vid=${l3_device##*.}
			[ $wanv6_vid -ge 0 ] || wanv6_vid=$WAN_DEFUALT_VID
			[ -x "/usr/bin/hw_nat" ] && hw_nat -W 1_${wanv6_vid}
		else
			[ -x "/usr/bin/hw_nat" ] && hw_nat -W 0
		fi
		iwpriv ra0 set hw_nat_register=1 >/dev/null 2>&1
		iwpriv rai0 set hw_nat_register=1 >/dev/null 2>&1
	}	
}

stop()
{
	#config_load wireless
	#config_foreach config_wifi_intf wifi-iface 0
	rmmod hw_nat >/dev/null 2>&1
}
