#!/bin/sh /etc/rc.common

START=66
#STOP=66

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
	service_start /usr/sbin/imbd
	fi

	return 0
}

stop() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
	service_stop /usr/sbin/imbd
	fi

	return 0
}
