#!/bin/sh /etc/rc.common

START=99

. /lib/led_night_mode/ledpm_core.sh
boot()
{
	ledpm_boot
}

start()
{
	ledpm_start
}

stop()
{
	ledpm_stop
}

restart()
{
	ledpm_restart
}

reload()
{
	ledpm_reload
}
