#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=48

start() {
    #if [ ! -e usr/bin/openssl ]; then
    #    luarsa_keys_gen
    #fi
}

restart() {
    #if [ ! -e usr/bin/openssl ]; then
    #   luarsa_keys_gen
    #fi
}

reload() {
    #if [ ! -e usr/bin/openssl ]; then  
    #   luarsa_keys_gen
    #fi
}
