#!/bin/sh /etc/rc.common
# Copyright(c) 2011-2013 Shenzhen TP-LINK Technologies Co.Ltd.
# file     nat.init
# brief    
# author   Guo Dongxian
# version  1.0.0
# date     26Feb14
# histry   arg 1.0.0, 26Feb14, Guo Dongxian, Create the file. 

START=46

NAT_LIBDIR=/lib/nat

nat() {
	. $NAT_LIBDIR/nat_core.sh
	nat_$1 $2

}

start() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
	nat start $1
	fi
}

stop() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
	nat stop $1
	fi
}

restart() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
	nat restart $1
	fi
}

reload() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
	nat reload $1
	fi
}

