#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=47

PC_LIBDIR=/lib/parental_control

pc() {
	. $PC_LIBDIR/core.sh
	fw_$1
}

start() {
	if [ ! -f /etc/config/parental_control_v2 ];then
		touch /etc/config/parental_control_v2
		touch /etc/config/history_list
		touch /etc/config/client_mgmt
		uci commit
	fi
	pc start
}

stop() {
	pc stop
}

restart() {
	pc restart
}

reload() {
	pc reload
}
