#!/bin/sh /etc/rc.common

START=51

SERVICE_DAEMONIZE=1
start()
{
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"

	local onemesh_enable=$(uci get onemesh.onemesh.enable)
	if [ -z "$onemesh_enable" ]; then
		onemesh_enable="on"
	fi

	if [ "$sysmode" = "router" -a "$onemesh_enable" = "on" ]; then
		service_start "/bin/nice" -n -5 /usr/bin/sync-server
	fi
}

stop()
{
	service_stop /usr/bin/sync-server
}
