#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org 

START=39
start() {
	local enable=`uci get wireless.wlan0.usb_interference_reduction`
	if [ -n "$enable" -a -f "/lib/usb/reduction.sh" ]; then
		/lib/usb/reduction.sh $enable
	fi
	
	[ -d /proc/bus/usb ] && {
		/bin/mount -t usbfs none /proc/bus/usb
	}	
}