#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=48

WIRELESS_SCHEDULE_LIBDIR=/lib/wifi

wireless_schedule() {
	. ${WIRELESS_SCHEDULE_LIBDIR}/wireless_schedule_core.sh
	wireless_schedule_$1
}

start() {
	wireless_schedule start
}

stop() {
	wireless_schedule stop
}

restart() {
	wireless_schedule restart
}
