#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=99
STOP=10

MONIT_BIN="/usr/sbin/monit"

ROOT_CRONTAB="/etc/crontabs/root"
TMP_CRONTAB="/tmp/monit_cron"

MUNITE=1

start() {
	local sysmode
	config_load "sysmode"	
	config_get sysmode sysmode mode  
	[ x"$sysmode" != x"router" ] && exit 1	
	
	local new_cron_item="*/${MUNITE} * * * * sh $MONIT_BIN"
	local cron_item=`grep "$MONIT_BIN" ${ROOT_CRONTAB}`
	[ "${cron_item}" != "${new_cron_item}" ] && {		
		echo "${new_cron_item}" > ${TMP_CRONTAB}
		crontab -l | grep -v "$MONIT_BIN" | cat - "${TMP_CRONTAB}" | crontab -		
		rm -f ${TMP_CRONTAB}
	}
}

stop() {
	crontab -l | grep -v "$MONIT_BIN" | crontab -
}

restart() {
	stop
	start $@
}

