#!/bin/sh /etc/rc.common
# Copyright (C) 2017 Tp-link.com
# Author: Xu Shengfu <xushengfu@tp-link.com.cn>
# Date: 27Nov17

START=99

PROG=/usr/sbin/conn-indicator

. /lib/functions.sh

start() {
     service_start $PROG &
}
