#!/bin/sh
# Copyright(c) 2008-2014 Shenzhen TP-LINK Technologies Co.Ltd.
#
# Details : Auto detection script.
# Author  : Ye Qianchuan <yeqianchuan@tp-link.net>
# Version : 1.0
# Date    : 25 Mar, 2014

export DHCP_TIMEOUT=3
export DHCP_RETRIES=3

export PPPOE_TIMEOUT=3
export PPPOE_RETRIES=3

export INTERNET_TIMEOUT=2
export DNS_TIMEOUT=5
export DNS_V6_TIMEOUT=2

export DSLITE_AFTR_LIST_PRIVATE=$(uci get protocol.dslite.AFTR_name_list_private)
export DSLITE_AFTR_LIST_PUBLIC=$(uci get protocol.dslite.AFTR_name_list_public)
export DSLITE_DOMAIN=gw.transix.jp
export V6PLUS_DOMAIN_JPNE=api.enabler.ne.jp
export V6PLUS_DOMAIN_OCN=rule.map.ocn.ad.jp

AFTR_NUM=$(expr $(echo $DSLITE_AFTR_LIST_PRIVATE |wc -w) + $(echo $DSLITE_AFTR_LIST_PUBLIC |wc -w))
export EST_TIME=$(expr 60 + $AFTR_NUM  \* $DNS_V6_TIMEOUT \* 2)
export CHECK_URL=tp-link.com
export RESULT_FILE=/tmp/autodetect

export DHCP_ALIAS=1
export PPPOE_ALIAS=2

(
    flock -n 9 || exit 0
    echo time $((EST_TIME*1000)) > "$RESULT_FILE"
    /lib/autodetect/autodetect.sh $@ &
) 9>/var/run/autodetect.lock
