#!/usr/bin/lua

-- get new firmware list from cloud.
local cloud_getFirmware = require "cloud_req.cloud_getFirmware"
local dbg   = require "luci.tools.debug"
local uci_r = require("luci.model.uci").cursor()

--retry count when fail, and just try once if no input
local retrycount = 1
local ret, error_code = cloud_getFirmware.get_fwlist(retrycount)

-- exit with error code or 0
if not ret then
	if error_code == -1000 then
		os.exit(1)
	elseif error_code == -5000 then
		os.exit(2)
	else
		os.exit(3)
	end
else
	os.exit(0)
end
