#!/usr/bin/lua

local cloud = require "cloud_req.cloud_comm"
local sys   = require "luci.sys"
local fs    = require "luci.fs"

local CLOUD_GEN_SVRFILE_BIN = "/usr/sbin/cloud_genSrvFile"

if fs.isfile(CLOUD_GEN_SVRFILE_BIN) then
	sys.fork_call(CLOUD_GEN_SVRFILE_BIN)

	local event = 12
	cloud.cloud_notify(event)
end
