#!/usr/bin/lua
--[[
Copyright(c) 2018-2023 Shenzhen TP-LINK Technologies Co.Ltd.

File    : logwrite
Details : System log writer.
Author  : Zeng Wei <zengwei@tp-link.com.cn>
Version : 1.0
Date    : 4 DEC, 2018
]]--

local logm  = require "luci.model.log"

if #arg < 3 then
    return
end

local pid = arg[1]
local proj_name = arg[2]
local msg_macrostr = arg[3]

-- Parse args.
local params = {}
local i = 4
while i <= #arg do
    params[#params + 1] = arg[i]
    i = i + 1
end

local log = logm.Logn(proj_name)
log(log.logid[msg_macrostr], unpack(params))

