#!/bin/sh
# Copyright (C) 2009 OpenWrt.org


# "proc_name init_file pid_file"
source /lib/monit/monit_proclist


find_pid() {
	local mproc=$1
	local proclist=`ls -d /proc/[0-9]*`
	for proc in $proclist
	do
		[ -f $proc/comm ] && {
			local procname=`cat $proc/comm`
			[ "x$mproc" = "x$procname" ] && {
				echo ${proc##*/}
				return
			} 
		}
	done
	echo -1
	return
}

check_proc() {    
	local proc_name=$1
	local init_file=$2
	local pid_file=$3
	
	[ -f "$pid_file" ] && {
		#echo "${proc_name}: read pid file $pid_file" > /dev/console
		local tmp_pid=`cat $pid_file`
		[ -n $tmp_pid ] && [ -d "/proc/$tmp_pid" ] && [ x"$proc_name" = x"`cat /proc/$tmp_pid/comm`" ] && return		
	}
	#echo "${proc_name}: no pid file or nomatch" > /dev/console
	
	local newpid=`find_pid $proc_name`
	[ $newpid != -1 ] && {
		#echo "${proc_name}: update pid file" > /dev/console
		echo $newpid > "$pid_file" && return
	}	

	#echo "${proc_name}: proc not found, to restart" > /dev/console
	/etc/init.d/$init_file restart
}

check_proc_list() {	
	for mproc in $mproclist
	do
        local args=`eval echo '$'$mproc`        
		check_proc $args
	done
}

check_proc_list
