#!/bin/sh
. /lib/functions.sh

config_load /etc/config/network
config_get wan_type wan wan_type

## is_online: 1--online; 0--offline
ONLINE_STATUS_FILE="/tmp/is_online"
ONLINE_V6_STATUS_FILE="/tmp/is_online_v6"

get_online_status()
{
	local result
	local tryTimes=0

## avoid read error result, re-read most 3 times
	while [ $tryTimes -lt 3 -a "$result" != "0" -a "$result" != "1" ]; do
		result=`cat $ONLINE_STATUS_FILE`
		if [ "$wan_type" == "v6plus" ]; then
			result=`cat $ONLINE_V6_STATUS_FILE`
		fi
		let "tryTimes = $tryTimes + 1"
	done

	if [ "$result" == "1" ]; then
		return 0
	else
		return 1
	fi
}

get_online_status