#!/bin/sh
[ -f "/etc/init.d/tm_shn" ] || exit 0
. /lib/functions.sh
config_load tfstats
config_get tfs_en switch enable "off"


qos_enable=$(uci_get_state tm_qos core qos_real_up)

if [ "$tfs_en" = "on" -o "$qos_enable" = "1" ]; then 
	lsmod |grep -q "hw_nat"  &&  /etc/init.d/hnat-start stop
else
	lsmod |grep -q "hw_nat"  || /etc/init.d/hnat-start start
fi

