#!/bin/sh
. /lib/functions.sh
. /lib/netifd/netifd-proto.sh

IFNAME=$ifname
STATE=$new_dhcpc_state
ADDR6_FILE=/tmp/autodetect_addr6

echo IFNAME=$ifname STATE=$new_dhcpc_state > /dev/console
[ -z "$IFNAME" ] && exit 1

deconfig_interface() {
	[ -n "$ADDR6_FILE" ] && {
		ifconfig $IFNAME del $(cat $ADDR6_FILE)/64		
		rm $ADDR6_FILE
	}
}

setup_interface () {
	DNS2=${new_domain_name_servers##*[, ]}
	DNS1=${new_domain_name_servers%%[, ]*}

	[ -n "$DNS1" ] && echo $DNS1 > /tmp/dns1
	[ -n "$DNS1" -a -n "$DNS2" -a "$DNS1" != "$DNS2" ] && echo $DNS2 > /tmp/dns2

	echo ++++++++++++++++++++++ > /dev/console
	echo DNS1=$DNS1 DNS2=$DNS2  > /dev/console
	echo ++++++++++++++++++++++ > /dev/console

	mbit=`cat /proc/sys/net/ipv6/conf/$IFNAME/ndisc_mbit`

	if [ $mbit -eq 1 -a -n "$new_ip6prefix" -a -z "$new_ip6addr" ]; then
		new_ip6addr=${new_ip6prefix%?}
		new_ip6addr=${new_ip6addr%?}
		count1=`echo $new_ip6addr |tr -cd : |wc -c`
		let "count=3 - $count1"

		while [ $count -ne 0 ]; do
			new_ip6addr=${new_ip6addr}:0
			let "count=count - 1"
		done

		while read line
		do
			[ $IFNAME != ${line##* } ] && continue
			[ "fe80" = ${line:0:4} ] && {
				element=${line:0:32}
				new_ip6addr=${new_ip6addr}:${element:16:4}:${element:20:4}:${element:24:4}:${element:28:4}
				echo autodetect:new_ip6addr[consist of pd] is : $new_ip6addr > /dev/console
			}
		done </proc/net/if_inet6
	fi
	
	ifconfig $IFNAME add $new_ip6addr/64 && echo $new_ip6addr > $ADDR6_FILE
}

case "$STATE" in
	"2" | "3")
		setup_interface
	;;

	"6")
		deconfig_interface
	;;
esac

exit 0
