#!/bin/sh
# Copyright (C) 2009-2012 OpenWrt.org
# Copyright (C) 2010 Vertical Communications
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

[ "$ACTION" = "ifdown" ] && {
	[ -f /proc/tplink/hwnat ] && echo f > /proc/tplink/hwnat
}

