#!/bin/sh

if [ "$INTERFACE" != "lan" ]; then
    exit 0
fi

if [ "$ACTION" = "ifup" ]; then
    #first stop avahi-daemon anyway
    /etc/init.d/avahi-daemon stop

	#check if start
	sh /lib/time_machine/tm_ifup.sh &
fi
