#!/bin/sh

if [ "$ACTION" != "ifup" ];then
	exit 0
fi

if [ "$INTERFACE" = "wan" -o "$INTERFACE" = "internet"  -o "$INTERFACE" = "mobile" ];then
	. /lib/functions.sh
	SYS_SET_TIME=$(uci_get_state systime core sync)
	if [ "$SYS_SET_TIME" -eq 0 ];then
		pgrep ntpd && /etc/init.d/sysntpd restart >/dev/null
	fi
fi
