#!/bin/sh

[ "ifup" = "$ACTION" ] && {
    if [ "wan" = "$INTERFACE" -o "internet" = "$INTERFACE" ]; then
        if [ $(ps w|grep -v grep|grep -w cwmp -c) -gt 0 ]; then
            /etc/init.d/cwmp reload generate_conf
            cwmp_cli -u wan
        else
            /etc/init.d/cwmp reload
        fi
    fi
}
