#!/bin/sh /etc/rc.common
#port from MTK SDK, remove unused code.
#=============================================================================
# smp_affinity: 1 = CPU1, 2 = CPU2, 3 = CPU3, 4 = CPU4
# rps_cpus: wxyz = CPU3 CPU2 CPU1 CPU0 (ex:0xd = 0'b1101 = CPU1, CPU3, CPU4)
#=============================================================================

START=99

APCLI_RTDEV="0"
OPTIMIZED_FOR="wifi"
CONFIG_RALINK_MT7621="y"
GE1_IF="eth0"
GE2_IF="eth1"

LIST=`cat /proc/interrupts | sed -n '1p'`
NUM_OF_CPU=0; for i in $LIST; do NUM_OF_CPU=`expr $NUM_OF_CPU + 1`; done;
PHY_POS=`expr $NUM_OF_CPU + 3` #physical irq # position in /proc/interrups may vary with the number of CPU up

start_smp(){
	if [ $OPTIMIZED_FOR == "wifi" ]; then
		if [ $NUM_OF_CPU == "4" ]; then
			if [ "$CONFIG_RALINK_MT7621" = "y" ]; then
				echo 2 > /proc/irq/3/smp_affinity  #GMAC
				echo 4 > /proc/irq/4/smp_affinity  #PCIe0
				echo 8 > /proc/irq/24/smp_affinity #PCIe1
				echo 8 > /proc/irq/25/smp_affinity #PCIe2
				echo 8 > /proc/irq/19/smp_affinity #VPN
				echo 8 > /proc/irq/20/smp_affinity #SDXC
				echo 2 > /proc/irq/22/smp_affinity #USB

				echo 3 > /sys/class/net/ra0/queues/rx-0/rps_cpus
				echo 3 > /sys/class/net/apcli0/queues/rx-0/rps_cpus
				echo 3 > /sys/class/net/wds0/queues/rx-0/rps_cpus
				echo 3 > /sys/class/net/wds1/queues/rx-0/rps_cpus
				echo 3 > /sys/class/net/wds2/queues/rx-0/rps_cpus
				echo 3 > /sys/class/net/wds3/queues/rx-0/rps_cpus
					
				echo 3 > /sys/class/net/rai0/queues/rx-0/rps_cpus
				echo 3 > /sys/class/net/apclii0/queues/rx-0/rps_cpus
				echo 3 > /sys/class/net/wdsi0/queues/rx-0/rps_cpus
				echo 3 > /sys/class/net/wdsi1/queues/rx-0/rps_cpus
				echo 3 > /sys/class/net/wdsi2/queues/rx-0/rps_cpus
				echo 3 > /sys/class/net/wdsi3/queues/rx-0/rps_cpus
				if [ -d "/sys/class/net/rai0" ]; then
					echo 5 > /sys/class/net/$GE1_IF/queues/rx-0/rps_cpus
					echo 5 > /sys/class/net/$GE2_IF/queues/rx-0/rps_cpus
					echo "$GE1_IF/$GE2_IF RPS: CPU0/2"
				else
					echo 3 > /sys/class/net/$GE1_IF/queues/rx-0/rps_cpus
					echo 3 > /sys/class/net/$GE2_IF/queues/rx-0/rps_cpus			
					echo "$GE1_IF/$GE2_IF RPS: CPU0/1"	                        
				fi
							
				if [ -d "/sys/class/net/rai0" ]; then
					if [ "$APCLI_RTDEV" = "1" ]; then
						echo "MT7621 2Card DBDC RP MODE"
						echo 2 > /proc/irq/4/smp_affinity
						echo 4 > /proc/irq/24/smp_affinity
						echo 9 > /sys/class/net/ra0/queues/rx-0/rps_cpus
						echo 9 > /sys/class/net/rax0/queues/rx-0/rps_cpus
						echo 9 > /sys/class/net/rai0/queues/rx-0/rps_cpus
						echo 9 > /sys/class/net/apclii0/queues/rx-0/rps_cpus
						echo 5 > /sys/class/net/$GE1_IF/queues/rx-0/rps_cpus
						echo 5 > /sys/class/net/$GE2_IF/queues/rx-0/rps_cpus
					else
						echo "MT7621 2Card DBDC AP MODE"
						echo 4 > /proc/irq/4/smp_affinity
						echo 8 > /proc/irq/24/smp_affinity
						echo 3 > /sys/class/net/ra0/queues/rx-0/rps_cpus
						echo 3 > /sys/class/net/rax0/queues/rx-0/rps_cpus
						echo 3 > /sys/class/net/rai0/queues/rx-0/rps_cpus
						echo 9 > /sys/class/net/$GE1_IF/queues/rx-0/rps_cpus
						echo 9 > /sys/class/net/$GE2_IF/queues/rx-0/rps_cpus
					fi
				else
					echo "MT7621 1Card DBDC"
					if [ -d "/sys/class/net/rax0" ]; then
						echo 3 > /sys/class/net/rax0/queues/rx-0/rps_cpus
					else
						echo 3 > /sys/class/net/ra1/queues/rx-0/rps_cpus
					fi
	
					if [ -d "/sys/class/net/apclix0" ]; then
						echo 3 > /sys/class/net/apclix0/queues/rx-0/rps_cpus
					else
						echo 3 > /sys/class/net/apcli1/queues/rx-0/rps_cpus
					fi
					echo 8 > /proc/irq/4/smp_affinity  #PCIe0
					echo 5 > /sys/class/net/$GE1_IF/queues/rx-0/rps_cpus
					echo 5 > /sys/class/net/$GE2_IF/queues/rx-0/rps_cpus
				fi
			fi
		elif [ $NUM_OF_CPU == "2" ]; then
			if [ "$CONFIG_RALINK_MT7621" = "y" ]; then
				echo 2 > /proc/irq/3/smp_affinity  #GMAC
				echo 1 > /proc/irq/4/smp_affinity  #PCIe0
				echo 2 > /proc/irq/24/smp_affinity #PCIe1
				echo 2 > /proc/irq/25/smp_affinity #PCIe2
				echo 1 > /proc/irq/19/smp_affinity #VPN
				echo 1 > /proc/irq/20/smp_affinity #SDXC
				echo 1 > /proc/irq/22/smp_affinity #USB

				echo 2 > /sys/class/net/ra0/queues/rx-0/rps_cpus
				echo 1 > /sys/class/net/rai0/queues/rx-0/rps_cpus
				echo 2 > /sys/class/net/apcli0/queues/rx-0/rps_cpus
				echo 1 > /sys/class/net/apclii0/queues/rx-0/rps_cpus

				echo 2 > /sys/class/net/$GE1_IF/queues/rx-0/rps_cpus
				echo 2 > /sys/class/net/$GE2_IF/queues/rx-0/rps_cpus
            fi
		fi
	elif [ $OPTIMIZED_FOR == "storage" ]; then
		if [ $NUM_OF_CPU == "4" ]; then
			if [ "$CONFIG_RALINK_MT7621" = "y" ]; then
				echo 1 > /proc/irq/3/smp_affinity  #GMAC Tx/Rx
				echo 2 > /proc/irq/4/smp_affinity  #PCIe0
				echo 2 > /proc/irq/24/smp_affinity #PCIe1
				echo 2 > /proc/irq/25/smp_affinity #PCIe2
				echo 4 > /proc/irq/19/smp_affinity #VPN
				echo 4 > /proc/irq/20/smp_affinity #SDXC
				echo 4 > /proc/irq/22/smp_affinity #USB
				echo 2 > /sys/class/net/ra0/queues/rx-0/rps_cpus
				echo 2 > /sys/class/net/rai0/queues/rx-0/rps_cpus
				echo 2 > /sys/class/net/$GE1_IF/queues/rx-0/rps_cpus
				#echo 2 > /sys/class/net/$GE1_IF.2/queues/rx-0/rps_cpus # should change back to $GE2_IF in the future
				echo 2 > /sys/class/net/$GE2_IF/queues/rx-0/rps_cpus
			fi
		elif [ $NUM_OF_CPU == "2" ]; then
			if [ "$CONFIG_RALINK_MT7621" = "y" ]; then
				echo 1 > /proc/irq/3/smp_affinity  #GMAC
				echo 1 > /proc/irq/4/smp_affinity  #PCIe0
				echo 1 > /proc/irq/24/smp_affinity #PCIe1
				echo 1 > /proc/irq/25/smp_affinity #PCIe2
				echo 1 > /proc/irq/19/smp_affinity #VPN
				echo 1 > /proc/irq/20/smp_affinity #SDXC
				echo 1 > /proc/irq/22/smp_affinity #USB
				echo 1 > /sys/class/net/ra0/queues/rx-0/rps_cpus
				echo 1 > /sys/class/net/rai0/queues/rx-0/rps_cpus
				echo 1 > /sys/class/net/$GE1_IF/queues/rx-0/rps_cpus
				#echo 1 > /sys/class/net/$GE1_IF.2/queues/rx-0/rps_cpus # should change back to $GE2_IF in the future
				echo 1 > /sys/class/net/$GE2_IF/queues/rx-0/rps_cpus
			fi
		fi
	else
		echo "unknow arguments!"
		exit 0
	fi
}

start() {
	start_smp
	return 0
}

restart() {
	return 0
}

stop() {
	return 0
}

reload() {
	return 0
}
