#!/bin/sh /etc/rc.common

START=99zzzz
STOP=90


boot() {
	## set phy_auto_up flag to make phy up automatically when restart network
	echo 1 > /proc/mt7621/phy_auto_up
	touch /tmp/dut_bootdone
	echo 3 > /proc/sys/vm/drop_caches
	echo "drop caches" > /dev/console
}

start() {
    return 0
}

stop() {
    return 0
}
