#!/bin/sh

is_calibrated(){
        /sbin/is_cal
}

if [ "$(is_calibrated)" = "true" ]; then

#if [ "$(uci get ledctrl.NIGHT.enable)" == "off" ] ;
#then
	if [ "$(uci get ledctrl.GENERAL.enable)" == "on" ]
	then
		uci set ledctrl.GENERAL.enable="off"
	else
		uci set ledctrl.GENERAL.enable="on"
	fi

	uci commit ledctrl
	ledcli GENERAL
#fi

else
        if [ ! -e /tmp/btn_check ]; then
                echo 0 > /tmp/btn_check
        fi
        ret=$(cat /tmp/btn_check)
        ret=$(($ret | 0x4))
        echo $ret > /tmp/btn_check
fi
